Added various options for overriding defaults, deleting the iptables chain, and only downloading the blocklists without updating iptables (and vice versa).

diff --git a/spamhaus-drop b/spamhaus-drop
--- a/spamhaus-drop
+++ b/spamhaus-drop
@@ -13,64 +13,186 @@ IPTABLES="/sbin/iptables"
 # list of known spammers
 URLS="www.spamhaus.org/drop/drop.lasso www.spamhaus.org/drop/edrop.lasso"
 
-# save local copy here
-FILE="/tmp/drop.lasso"
+# local cache copy
+CACHE_FILE="/tmp/drop.lasso"
 
-# iptables custom chain
+# iptables custom chain name
 CHAIN="Spamhaus"
 
-# check to see if the chain already exists
-$IPTABLES -L "$CHAIN" -n
+# (don't) skip failed blocklist downloads
+SKIP_FAILED_DOWNLOADS=0
 
-# check to see if the chain already exists
-if $IPTABLES -L "$CHAIN" -n
-then
-    # flush the old rules
-    $IPTABLES -D INPUT -j "$CHAIN"
-    $IPTABLES -D FORWARD -j "$CHAIN"
-    $IPTABLES -F "$CHAIN"
+# log blocklist hits in iptables
+LOG_BLOCKLIST_HITS=1
 
-    # Check is script is run with some kind of flag (like 'deletechain' for example)
-    if [ -n "$1" ]
-    then
-        $IPTABLES -X "$CHAIN"
-        echo "$CHAIN removed in iptables."
-        exit
-    else
-        echo "Flushed old rules. Applying updated Spamhaus list...."
-    fi
-else
-    # create a new chain set
-    $IPTABLES -N "$CHAIN"
+error() {
+	echo "$1" 1>&2
+}
 
-    # tie chain to input rules so it runs
-    $IPTABLES -A INPUT -j "$CHAIN"
+die() {
+	if [ -n "$1" ]; then
+		error "$1"
+	fi
+	exit 1
+}
 
-    # don't allow this traffic through
-    $IPTABLES -A FORWARD -j "$CHAIN"
+usage() {
+	echo "Basic usage: $(basename $0) <-u>
 
-    echo "Chain not detected. Creating new chain and adding Spamhaus list...."
-fi;
+Additional options and arguments:
+  -c=CHAIN_NAME        Override default iptables chain name
+  -l=URL_LIST          Override default block list URLs [careful!]
+  -f=CACHE_FILE_PATH   Override default cache file path
+  -s                   Skip failed blocklist downloads, continuing instead of aborting
+  -z                   Update the blocklist from the local cache, don't download new entries
+  -d                   Delete the iptables chain (removing all blocklists)
+  -o                   Only download the blocklists, don't update iptables
+  -t                   Disable logging of blocklist hits in iptables
+  -h                   Display this help message
+"
+	exit $EXIT_CODE
+}
 
-for URL in $URLS; do
-    # get a copy of the spam list
-    echo "Fetching $URL ..."
-    wget -qc "$URL" -O "$FILE"
-    tail "$FILE"
+set_mode() {
+	if [ -n "$MODE" ]; then
+		die "You must only specify one of -u/-c/-d"
+	fi
+	MODE="$1"
+}
 
-    # iterate through all known spamming hosts
-    for IP in $( cat "$FILE" | egrep -v '^;' | cut -d' ' -f1 ); do
-        # add the ip address log rule to the chain
-        $IPTABLES -A "$CHAIN" -p 0 -s "$IP" -j LOG --log-prefix "[SPAMHAUS BLOCK]" -m limit --limit 3/min --limit-burst 10
+delete_chain() {
+	$IPTABLES -X "$CHAIN"
+	echo "'$CHAIN' chain removed from iptables."
+}
 
-        # add the ip address to the chain
-        $IPTABLES -A "$CHAIN" -p 0 -s "$IP" -j DROP
+download_rules() {
+	TMP_FILE="$(tempfile)"
+	
+	for URL in $URLS; do
+		# get a copy of the spam list
+		echo "Fetching '$URL' ..."
+		curl -Ss "$URL" | grep -e "" | tee -a "$TMP_FILE" > /dev/null
+		if [ ${PIPESTATUS[0]} -ne 0 ]; then
+			if [ $SKIP_FAILED_DOWNLOADS -eq 1 ]; then
+				echo "Failed to download '$URL' while skipping is enabled - so continuing."
+			else
+				rm -f "$TMP_FILE"
+				die "Failed to download '$URL', aborting."
+			fi
+		fi
+	done
 
-        echo "$IP"
-    done
+	mv -f "$TMP_FILE" "$CACHE_FILE"
+	rm -f "$TMP_FILE"
+}
 
-    # remove the spam list
-    unlink "$FILE"
+update_iptables() {
+	# refuse to run if the cache file looks insane
+	if [ ! -r "$CACHE_FILE" ]; then
+		die "Cannot read cache file '$CACHE_FILE'"
+	elif [ "$(stat -c '%U' "$CACHE_FILE")" != "root" ]; then
+		die "Cache file '$CACHE_FILE' is not owned by root.  Refusing to load it."
+	fi
+
+	# check to see if the chain already exists
+	if $IPTABLES -L "$CHAIN" -n; then
+		# flush the old rules
+		$IPTABLES -D INPUT -j "$1"
+		$IPTABLES -D FORWARD -j "$1"
+		$IPTABLES -F "$CHAIN"
+
+		echo "Flushed old rules. Applying updated Spamhaus list...."
+	else
+		# create a new chain set
+		$IPTABLES -N "$CHAIN"
+
+		# tie chain to input rules so it runs
+		$IPTABLES -A INPUT -j "$CHAIN"
+
+		# don't allow this traffic through
+		$IPTABLES -A FORWARD -j "$CHAIN"
+
+		echo "'$CHAIN' chain not detected. Creating new chain and adding Spamhaus list...."
+	fi;
+
+	# iterate through all known spamming hosts
+	for IP in $( cat "$CACHE_FILE" | egrep -v '^;' | cut -d' ' -f1 ); do
+		if [ $LOG_BLOCKLIST_HITS -eq 1 ]; then
+			# add the ip address log rule to the chain
+			$IPTABLES -A "$CHAIN" -p 0 -s "$IP" -j LOG --log-prefix "[SPAMHAUS BLOCK]" -m limit --limit 3/min --limit-burst 10
+		fi
+
+		# add the ip address to the chain
+		$IPTABLES -A "$CHAIN" -p 0 -s "$IP" -j DROP
+
+		echo "$IP"
+	done
+
+	echo "'$CHAIN' chain updated with latest rules."
+}
+
+download_rules_and_update_iptables() {
+	download_rules
+	update_iptables
+}
+
+if [ "$(whoami)" != "root" ]; then
+	die "You must run this command as root."
+fi
+
+while getopts "zhoudtl:sc:f:" option; do
+	case "$option" in
+		c)	# override chain name
+			CHAIN="$OPTARG"
+			;;
+		
+		l)  # override list of block list URLs
+			URLS="$OPTARG"
+			;;
+		
+		u)  # update block list
+			set_mode download_rules_and_update_iptables
+			;;
+		
+		s)  # skip failed blocklist downloads
+			SKIP_FAILED_DOWNLOADS=1
+			;;
+		
+		o)  # download the rules to the cache file, and don't update iptables
+			set_mode download_rules
+		    ;;
+		
+		d)  # delete the iptables chain
+			set_mode delete_chain
+		    ;;
+
+		t)  # disable iptables logging
+			LOG_BLOCKLIST_HITS=0
+			;;
+		
+		z)  # update iptables from local cache without downloading
+		    set_mode update_iptables
+			;;
+		
+		h)  # show usage information
+		    usage
+		    ;;
+		
+		:)
+			error "Error: -${OPTARG} requires an argument."
+			usage
+			die
+			;;
+		
+		*)
+			error "Invalid argument -${OPTARG} supplied."
+			usage
+			die
+			;;
+	esac
 done
 
-echo "Done!"
+if [ ! -n "$MODE" ]; then
+	usage 1
+fi
+$MODE
